---
:api:
    :port: 9292
    :listen: "0.0.0.0"
:core:
    :iface: "eth0"

:database:
    :host: "127.0.0.1"

:assets: "../../config/assets"
:services: "../../config/services.yml"
:shared_secret: "mysupersecret"
