---
# Configuration of the REST API, TCP connection
:api:
    :listen: "0.0.0.0"
    :port: 1664

# Configuration for the internal communication, UDP connection
:core:
    :listen: "0.0.0.0"
    :port: 1664
    :pool_size: 20      # Maximum of simultaneous workers to run checks by the Core

# Specify Redis host
:redis:
    :host: "127.0.0.1"

# Path of assets definitions direcory
:assets: "/etc/hukurou/assets"

# Configuration of global services
:services: 
    :definitions: "/etc/hukurou/core/services.yml"
    :max_age: 900
    :timeout: 30

# Shared secret between Core instances
:secret: "mysupersecret"
